import { jsPDF } from 'jspdf';

export const generateEvidencePDF = (evidenceData) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('PACKING EVIDENCE SUMMARY', 105, 20, { align: 'center' });

    // Horizontal line
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);

    let y = 35;

    // Order Information Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Order Information:', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Order ID: ${evidenceData.orderNumber}`, 25, y);
    y += 6;
    doc.text(`Order Date: ${new Date(evidenceData.orderDate).toLocaleString()}`, 25, y);
    y += 6;
    doc.text(`Customer: ${evidenceData.customerName}`, 25, y);
    y += 6;
    if (evidenceData.customerEmail) {
        doc.text(`Email: ${evidenceData.customerEmail}`, 25, y);
        y += 6;
    }
    if (evidenceData.customerPhone) {
        doc.text(`Phone: ${evidenceData.customerPhone}`, 25, y);
        y += 6;
    }

    y += 5;

    // Product Details Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Product Details:', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    evidenceData.products.forEach((product, index) => {
        doc.text(`${index + 1}. ${product.name} (SKU: ${product.sku}) - Qty: ${product.quantity} @ \u20B9${product.price}`, 25, y);
        y += 6;
    });

    y += 5;

    // Return/RTO Information Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Return/RTO Information:', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Type: ${evidenceData.returnType}`, 25, y);
    y += 6;
    doc.text(`Reason: ${evidenceData.returnReason}`, 25, y);
    y += 6;
    doc.text(`Status: ${evidenceData.returnStatus}`, 25, y);
    y += 6;
    doc.text(`Initiated: ${new Date(evidenceData.returnInitiated).toLocaleString()}`, 25, y);
    y += 6;

    y += 5;

    // Packing Evidence Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Packing Evidence:', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Packed Date: ${new Date(evidenceData.packedDate).toLocaleString()}`, 25, y);
    y += 6;
    doc.text(`Packed By: ${evidenceData.packedBy} (${evidenceData.packedByUsername})`, 25, y);
    y += 6;
    doc.text(`Video Duration: ${evidenceData.videoDuration} seconds`, 25, y);
    y += 6;
    doc.text(`Video Size: ${(evidenceData.videoSize / 1024 / 1024).toFixed(2)} MB`, 25, y);
    y += 6;

    // Video hash (split into multiple lines if needed)
    doc.text('Video Hash (SHA-256):', 25, y);
    y += 6;
    doc.setFontSize(8);
    doc.text(evidenceData.videoHash, 25, y);
    y += 6;

    y += 5;

    // Verification Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Verification:', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');

    // Video integrity with color
    if (evidenceData.videoIntegrity === 'VALID') {
        doc.setTextColor(0, 128, 0); // Green
        doc.text(`Video Integrity: ${evidenceData.videoIntegrity} ✓`, 25, y);
    } else {
        doc.setTextColor(255, 0, 0); // Red
        doc.text(`Video Integrity: ${evidenceData.videoIntegrity} ✗`, 25, y);
    }
    doc.setTextColor(0, 0, 0); // Reset to black
    y += 6;

    doc.text(`Export Date: ${new Date(evidenceData.exportDate).toLocaleString()}`, 25, y);
    y += 6;
    doc.text(`App Version: ${evidenceData.appVersion}`, 25, y);
    y += 10;

    // Footer note
    doc.setFontSize(9);
    doc.setFont(undefined, 'italic');
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Evidex - Proof-first packing & returns protection system', 20, y);
    y += 5;
    doc.text('IMPORTANT: This evidence package is read-only and tamper-proof.', 20, y);
    y += 5;
    doc.text('The video hash can be used to verify file integrity.', 20, y);

    return doc;
};

export const generateEvidenceJSON = (evidenceData) => {
    return JSON.stringify({
        orderInformation: {
            orderNumber: evidenceData.orderNumber,
            orderDate: evidenceData.orderDate,
            customerName: evidenceData.customerName,
            customerEmail: evidenceData.customerEmail,
            customerPhone: evidenceData.customerPhone,
        },
        productDetails: evidenceData.products,
        returnInformation: {
            type: evidenceData.returnType,
            reason: evidenceData.returnReason,
            status: evidenceData.returnStatus,
            initiated: evidenceData.returnInitiated,
        },
        packingEvidence: {
            packedDate: evidenceData.packedDate,
            packedBy: evidenceData.packedBy,
            packedByUsername: evidenceData.packedByUsername,
            videoDuration: evidenceData.videoDuration,
            videoSize: evidenceData.videoSize,
            videoHash: evidenceData.videoHash,
        },
        verification: {
            videoIntegrity: evidenceData.videoIntegrity,
            exportDate: evidenceData.exportDate,
            appVersion: evidenceData.appVersion,
        },
        note: 'This evidence package is read-only and tamper-proof. The video hash can be used to verify file integrity.',
    }, null, 2);
};
